[package]
name = "prometheus-network-metrics-exporter"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = "0.3"
prometheus = "0.13"
sysinfo = "0.30"

lazy_static = "1.4"
tokio = { version = "1", features = ["full"] }

